typography_spectrum: 0.46596617670729756
content_rating:
  adult: true
color:
  brandStrength: 0.406711756484583
  lightness: 0.06916967313736677
  saturation: 0.2125821835361421
  rhythmicContrast: 0.6595758271869272
  brandColors:
    - '#B9121B'
    - '#4C1B1B'
    - '#F6E497'
    - '#FCFAE1'
    - '#BD8D46'
layout_spectrum: 0.6922106412239373
name: Healistic Expectations
navigation:
  - name: Health & Wellness
    url: 'http://www.healisticexpectations.com/'
    type: external
  - name: Yoga & plant based cooking
    url: 'http://www.babylonsister.com/'
    type: external
title: Artfully seducing fear towards loving transformation
description: Healistic Expectations
