typography_spectrum: 0.4513045495841652
content_rating:
  adult: true
color:
  brandStrength: 0.00841528782621026
  lightness: 0.7130732550285757
  saturation: 0.44655437977053225
  rhythmicContrast: 0.46494036028161645
  brandColors:
    - '#B9121B'
    - '#4C1B1B'
    - '#F6E497'
    - '#FCFAE1'
    - '#BD8D46'
layout_spectrum: 0.4341813682112843
name: Healistic Expectations
navigation:
  - name: Health & Wellness
    url: 'http://www.healisticexpectations.com/'
    type: external
  - name: Yoga & plant based cooking
    url: 'http://www.babylonsister.com/'
    type: external
title: Artfully seducing fear towards loving transformation
description: Healistic Expectations
