typography_spectrum: 0.5224343226291239
content_rating:
  adult: true
color:
  brandStrength: 0.18877675686962903
  lightness: 0.5055619396734983
  saturation: 0.19415217102505267
  rhythmicContrast: 0.43954162718728185
  brandColors:
    - '#468966'
    - '#FFF0A5'
    - '#FFB03B'
    - '#B64926'
    - '#8E2800'
layout_spectrum: 0.4341813682112843
name: Healistic Expectations
navigation:
  - name: Health & Wellness
    url: 'http://www.healisticexpectations.com/'
    type: external
  - name: Yoga & plant based cooking
    url: 'http://www.babylonsister.com/'
    type: external
title: Healistic Expectations
description: Artfully seducing pain towards healing transformation
