typography_spectrum: 0.3999354434199631
content_rating:
  adult: true
color:
  brandStrength: 0.9089383068494499
  lightness: 0.21794071374461055
  saturation: 0.4562996169552207
  rhythmicContrast: 0.1278338802512735
  brandColors:
    - '#FF6138'
    - '#FFFF9D'
    - '#BEEB9F'
    - '#79BD8F'
    - '#00A388'
layout_spectrum: 0.4341813682112843
name: Healistic Expectations
navigation:
  - name: Health & Wellness
    url: 'http://www.healisticexpectations.com/'
    type: external
  - name: Yoga & plant based cooking
    url: 'http://www.babylonsister.com/'
    type: external
title: Artfully seducing fear towards loving transformation
description: Healistic Expectations
