typography_spectrum: 0.85031345509924
content_rating:
  adult: true
color:
  brandStrength: 0.25402648583985865
  lightness: 0.08943968825042248
  saturation: 0.5245748022571206
  rhythmicContrast: 0.961313450243324
  brandColors:
    - '#7D8A2E'
    - '#C9D787'
    - '#FFFFFF'
    - '#FFC0A9'
    - '#FF8598'
layout_spectrum: 0.5149171683005989
name: Healistic Expectations
navigation:
  - name: Health & Wellness
    url: 'http://www.healisticexpectations.com/'
    type: external
  - name: Yoga & plant based cooking
    url: 'http://www.babylonsister.com/'
    type: external
title: Artfully seducing fear towards loving transformation
description: Healistic Expectations
